### PR TITLE
Update deprecated packages, allow symfony/console ^5.0

### LINKED ISSUE #187: Add support for Symfony 4
Add support for Symfony console 4.x version, e.g.
```
"symfony/console": "^3.1.3 | ^4.0"
```

### PR DESCRIPTION
**Pull request by tadasaa**
The change removes deprecated kriswallsmith/assetic dependency, starts using assetic/framework (https://github.com/assetic-php/assetic).
Also allows newest symfony/console and fabpot/php-cs-fixer library versions. The only place where symfony console was used was the CLI commands, so the 'return 0;' exit code change seems to have been the only change that was necessary with newest symfony versions.
This fixes https://github.com/widmogrod/zf2-assetic-module/issues/187

### CODE REVIEW

**Comment by tadasauciunas** [comment]
Main purpose of this PR was to allow newest versions of symfony/console usage. Managed to get the travis builds running by upgrading the php, phpunit, phpcs fixer, other library versions. Let me know what you think @widmogrod

**Comment by widmogrod** [comment]
Hi @tadasauciunas, this is grate!

I and community will really appreciate this, especially that I no longer actively maintain this repository but I know that few people do. 

Thank you, grate job!

Since this is breaking change I release this change under version 3.0.0

**Comment by tadasaa** [comment]
Do you need any help with releasing the 3.0.0 version ? @widmogrod

**Comment by widmogrod** [comment]
Hi @tadasauciunas it's released:
https://packagist.org/packages/widmogrod/zf2-assetic-module#3.0.0
https://github.com/widmogrod/zf2-assetic-module/tree/3.0.0

**Comment by tadasaa** [comment]
Sorry, main github repository page didn't show it for some reason, my mistake :) Thanks

**Pull request merged**
