### PR TITLE
ZF3, EventManager 3 support

### PR DESCRIPTION
**Pull request by Saeven**
This PR solves the event manager crisis caused by the changes to ZF3's SM.  :)

Hooray! ZF3!

### CODE REVIEW

**Comment by tylkomat** [comment]
There are more open problems to make it running under ZF3.

The Initializers and Factories have not been updated to the new signatures. Also to make the console working one would need the package `zendframework/zend-mvc-console`, but with that package it is not compatible with ZF2. Another option would be to migrate to `zfcampus/zf-console`. That would make the console independent from `zend-mvc` package and backward compatible.

**Comment by widmogrod** [comment]
IMHO adapting signatures to ZF3 would be the best option. Then version of this project could be bumped to 2.0 and backward compatibility wouldn't be an issue, since anyone who needs previous version would use different version

@Saeven @tylkomat  would you like/mind to continue work on ZF3?

**Comment by tylkomat** [comment]
@widmogrod I don't mind. I anyway have a work in progress already, but there I was thinking to port to `zf-console`, since I noticed that the `mvc-console` has some issues see [here](https://github.com/zendframework/zend-mvc-console/issues/9) and [here](https://github.com/zendframework/zend-mvc-console/issues/10), which have the same reason I suppose.

**Comment by widmogrod** [comment]
@tylkomat sounds reasonable to use `zf-console`.

**Pull request merged**
